import type { Metadata } from "next";
import { Orbitron, Poppins } from "next/font/google";

const orbitron = Orbitron({ subsets: ["latin"], weight: "700", variable: "--font-orbitron" });
const poppins = Poppins({ subsets: ["latin"], weight: "400", variable: "--font-poppins" });

import "./globals.css";

export const metadata: Metadata = {
  title: "My Dream",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${poppins.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
